import 'bootstrap/dist/css/bootstrap.min.css';

import { AppContext } from '../features/context/App.context';
import { LogoutButton } from '../features/auth/components/Logout/LogoutButton';
export const metadata = {
  title: 'Welcome to pump-master',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppContext>
          <header className="d-flex align-items-center justify-content-between px-4 py-2 border-bottom mb-4">
            <h1 className="m-0">Pump Master</h1>
            <LogoutButton />
          </header>
          {children}
        </AppContext>
      </body>
    </html>
  );
}
