import 'bootstrap/dist/css/bootstrap.min.css';

import { AppContext } from '../features/context/App.context';
import { Header } from '../features/navigation/components/Header/Header';

export const metadata = {
  title: 'Welcome to pump-master',
  description: 'Generated by Shun',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppContext>
          <Header />
          {children}
        </AppContext>
      </body>
    </html>
  );
}
